# Generated by Django 6.0.2 on 2026-02-13 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Author",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("category", models.CharField(max_length=100)),
                ("tags", models.JSONField(default=list)),
                ("desc", models.TextField()),
                ("works", models.JSONField(default=list)),
                ("avatar_url", models.URLField(max_length=500)),
                ("details", models.TextField()),
                ("life_span", models.CharField(blank=True, max_length=100, null=True)),
                ("honors", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Novel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("author", models.CharField(max_length=255)),
                ("desc", models.TextField()),
                ("category", models.CharField(max_length=100)),
                ("tags", models.JSONField(default=list)),
            ],
        ),
        migrations.CreateModel(
            name="QuickLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("url", models.URLField(max_length=500)),
                ("desc", models.TextField()),
                ("category", models.CharField(max_length=100)),
                ("icon", models.URLField(blank=True, max_length=500, null=True)),
                ("detailed_desc", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Software",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("desc", models.TextField()),
                ("link", models.URLField(max_length=500)),
                ("tags", models.JSONField(default=list)),
                ("category", models.CharField(max_length=100)),
            ],
        ),
    ]
