# Generated by Django 6.0.2 on 2026-02-13 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="author",
            options={"verbose_name": "作者", "verbose_name_plural": "作者"},
        ),
        migrations.AlterModelOptions(
            name="novel",
            options={"verbose_name": "小说", "verbose_name_plural": "小说"},
        ),
        migrations.AlterModelOptions(
            name="quicklink",
            options={"verbose_name": "网站导航", "verbose_name_plural": "网站导航"},
        ),
        migrations.AlterModelOptions(
            name="software",
            options={"verbose_name": "软件", "verbose_name_plural": "软件"},
        ),
        migrations.AddField(
            model_name="novel",
            name="details",
            field=models.TextField(blank=True, default="", verbose_name="详细介绍"),
        ),
        migrations.AddField(
            model_name="software",
            name="details",
            field=models.TextField(blank=True, default="", verbose_name="详细介绍"),
        ),
        migrations.AlterField(
            model_name="author",
            name="avatar_url",
            field=models.URLField(max_length=500, verbose_name="头像链接"),
        ),
        migrations.AlterField(
            model_name="author",
            name="category",
            field=models.CharField(max_length=100, verbose_name="分类"),
        ),
        migrations.AlterField(
            model_name="author",
            name="desc",
            field=models.TextField(verbose_name="简介"),
        ),
        migrations.AlterField(
            model_name="author",
            name="details",
            field=models.TextField(verbose_name="详细介绍"),
        ),
        migrations.AlterField(
            model_name="author",
            name="honors",
            field=models.TextField(blank=True, null=True, verbose_name="荣誉"),
        ),
        migrations.AlterField(
            model_name="author",
            name="life_span",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="生卒年"
            ),
        ),
        migrations.AlterField(
            model_name="author",
            name="name",
            field=models.CharField(max_length=255, verbose_name="姓名"),
        ),
        migrations.AlterField(
            model_name="author",
            name="tags",
            field=models.JSONField(default=list, verbose_name="标签"),
        ),
        migrations.AlterField(
            model_name="author",
            name="works",
            field=models.JSONField(default=list, verbose_name="代表作"),
        ),
        migrations.AlterField(
            model_name="novel",
            name="author",
            field=models.CharField(max_length=255, verbose_name="作者"),
        ),
        migrations.AlterField(
            model_name="novel",
            name="category",
            field=models.CharField(max_length=100, verbose_name="分类"),
        ),
        migrations.AlterField(
            model_name="novel",
            name="desc",
            field=models.TextField(verbose_name="简介"),
        ),
        migrations.AlterField(
            model_name="novel",
            name="name",
            field=models.CharField(max_length=255, verbose_name="书名"),
        ),
        migrations.AlterField(
            model_name="novel",
            name="tags",
            field=models.JSONField(default=list, verbose_name="标签"),
        ),
        migrations.AlterField(
            model_name="quicklink",
            name="category",
            field=models.CharField(max_length=100, verbose_name="分类"),
        ),
        migrations.AlterField(
            model_name="quicklink",
            name="desc",
            field=models.TextField(verbose_name="描述"),
        ),
        migrations.AlterField(
            model_name="quicklink",
            name="detailed_desc",
            field=models.TextField(blank=True, null=True, verbose_name="详细描述"),
        ),
        migrations.AlterField(
            model_name="quicklink",
            name="icon",
            field=models.URLField(
                blank=True, max_length=500, null=True, verbose_name="图标链接"
            ),
        ),
        migrations.AlterField(
            model_name="quicklink",
            name="name",
            field=models.CharField(max_length=255, verbose_name="网站名"),
        ),
        migrations.AlterField(
            model_name="quicklink",
            name="url",
            field=models.URLField(max_length=500, verbose_name="链接"),
        ),
        migrations.AlterField(
            model_name="software",
            name="category",
            field=models.CharField(max_length=100, verbose_name="分类"),
        ),
        migrations.AlterField(
            model_name="software",
            name="desc",
            field=models.TextField(verbose_name="描述"),
        ),
        migrations.AlterField(
            model_name="software",
            name="link",
            field=models.URLField(max_length=500, verbose_name="链接"),
        ),
        migrations.AlterField(
            model_name="software",
            name="name",
            field=models.CharField(max_length=255, verbose_name="软件名"),
        ),
        migrations.AlterField(
            model_name="software",
            name="tags",
            field=models.JSONField(default=list, verbose_name="标签"),
        ),
    ]
